apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-service-account
  namespace: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-lease-role
  namespace: default
rules:
  - apiGroups: [ "","coordination.k8s.io" ]
    resources: [ "endpoints","leases" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: order-service-service-account-leader-election-lease-role
  namespace: default
subjects:
  - kind: ServiceAccount
    name: order-service-service-account
    namespace: default
roleRef:
  kind: Role
  name: leader-election-lease-role
  apiGroup: rbac.authorization.k8s.io
